### ISSUE TITLE
layout not detecting landscape vs portrait dynamically.

### ISSUE THREAD

**Issue by JakeDobson** [JakeDobson/VeritasHomesNW#23]
first load, portrait/compact will load fine. Switching to landscape will not send the offset, until the screen is touched.. 

Loading on landscape will not render correctly, until touching the screen, or switching to portrait and back to landscape...

Landscape loaded and switching to Portrait will not change the layout of the map, it keeps the position from landscape, until the screen is touched.

**Comment by JakeDobson** [comment]
zooming to locations is not centered...There seems to be different things going on based on what screen/orientation is loaded first.

**Comment by jordandobson** [comment]
What branch?

What devices have you tested this on? How can I reproduce?

I can make some assumptions but please be more clear and helpful in describing bugs.

**Comment by jordandobson** [comment]
"zooming to locations is not centered...There seems to be different things going on based on what screen/orientation is loaded first."

Yeah... we need to make sure we detect these things and make sure we are changing and updating classes when the resize event occurs. 

Have you done any debugging yet to see where the problem might be?

**Comment by jordandobson** [comment]
I see this issue now. I'll look to see how others handle this.
