### ISSUE TITLE
marker area zoom calculations

### ISSUE THREAD

**Issue by JakeDobson** [JakeDobson/VeritasHomesNW#3]
- we need to know the dimensions of the map and if it fits on the screen well
- If it doesn't...we may need to zoom in or out to make it fill the available area
- must handle updates on rotation and screen-size changes

**Comment by jordandobson** [comment]
@JakeDobson Is this resolved almost right? Just need to handle on Screen size changes?

**Comment by jordandobson** [comment]
Check check...

**Comment by JakeDobson** [comment]
I think we can close this one.
